export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const REGISTER = "REGISTER"

export const USERLIST = 'USERLIST'
export const USERUPDATE = 'USERUPDATE'

export const TOKENLIST = 'TOKENLIST'
export const TOKENLISTCREATE = 'TOKENLISTCREATE'
export const TOKENSLIST = 'TOKENSLIST'
export const TOKENUPDATE = 'TOKENUPDATE'
export const TOKENSTATUSUPDATE = 'TOKENSTATUSUPDATE'
export const GETTOKENBYID = 'GETTOKENBYID'


export const DEPOSITLIST = 'DEPOSITLIST'
export const WITHDRAWLIST = 'WITHDRAWLIST'

export const KYCLIST = 'KYCLIST'
export const KYCUPDATE = 'KYCUPDATE'



